### PR TITLE
Cloudflare integration

### PR DESCRIPTION
**Pull request by bradgarropy**

### CODE REVIEW

**Comment by bradgarropy** [comment]
This is no longer a work in progress, it's ready! You can see the deployed site [here](https://c5da4e08.new-remixaustin-com.pages.dev/).

**Comment by bradgarropy** [comment]
Closes #10 and #11.

**Comment by sethdavis512** [comment]
Mind educating a little here? Were these code changes pulled from the Cloudflare docs? Is that URL that you provided a branch build? Does Cloudflare offer branch builds? (I assume yes)...Approving so we can get this thing rolling.

**Comment by bradgarropy** [comment]
These changes are based on the template that Cloudflare provides, which is referenced in their [Remix documentation](https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/).

```zsh
npm create cloudflare@latest my-remix-app -- --framework=remix
```

I've also gone through this process for my personal website, which I documented the steps for [here](https://www.notion.so/bradgarropy/remix-x-cloudflare-2a5cb61153724f0a88062c0d7cfd846c).

The linked deployment is a link to a specific commit version of the site. Cloudflare also does branch builds, and integrates with pull requests as you would expect. You can see what the PR output looks like in the [comment above](https://github.com/remix-austin/new-remixaustin-com/pull/13#issuecomment-2168286851).

The next thing we need to figure out it Cloudflare account permissions. Once we link the domain name, then I can add additional members with particular permissions.

**Comment by sethdavis512** [comment]
THANKS BRAD! I appreciate the knowledge 🧠

**Pull request merged**
